---
# https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx
- name: Add certbot repository
  apt_repository:
    repo: "ppa:certbot/certbot"
    filename: certbot
    state: present
  register: certbot_repository_readied

- name: Install certbot for nginx
  when: certbot_repository_readied is success
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - software-properties-common
      - certbot
      - python-certbot-nginx
