---
# https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx
- name: Add certbot repository
  shell:
    cmd: "add-apt-repository universe"
  register: certbot_repository_readied

- name: Install certbot for nginx
  when: certbot_repository_readied is success
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - software-properties-common
      - certbot
      - python3-certbot-nginx
