version: '3'

services:
  ansible:
    build: ./ansible
    volumes:
      - "./ansible/ssh-config:/home/runner/.ssh/config"
      - "./ansible:/home/runner/ansible"
      - "./config/inventory.yml:/home/runner/ansible/inventory.yml"
