version: '3'

services:
  ansible:
    build: ./ansible
    volumes:
      - "./ansible/ssh-config:/home/runner/.ssh/config"
      - "./ansible:/home/runner/ansible"
      - "./config/hosts.yml:/home/runner/ansible/hosts.yml"
      - "./config/keys:/home/runner/ansible/keys"
      - "./config/nginx.conf.d:/home/runner/ansible/nginx.conf.d"
      - "./config/bin:/home/runner/ansible/bin"
      - "./config/bin:/home/runner/ansible/roles/tunneler/files/bin"
