---
- name: Create runner user
  user:
    name: runner
    shell: /usr/bin/env bash
  register: runner_created

- name: Setup ssh key for runner
  when: runner_created is success
  authorized_key:
    user=runner
    key="{{ lookup('file','./keys/id_ed25519.pub') }}"
