---
- name: Create bin directory for tunneling
  file:
    path: '~/tunnel/bin'
    state: directory
  become: yes
  become_user: tunneler

- name: Allow tunneler to control iptables
  copy:
    src: 'tunneler-sudoer.txt'
    dest: '/etc/sudoers.d/tunneler'
    mode: '0440'
    force: no

- name: Copy tunneling agent to bin
  copy:
    src: "bin/{{ item }}"
    dest: "~/tunnel/bin/{{ item }}"
    mode: '0755'
  become: yes
  become_user: tunneler
  loop:
    - shadowsocks2
    - gost

- name: Install Make
  apt:
    name: "make"

- name: Copy Makefile for tunneler
  copy:
    src: 'tunneler.mk'
    dest: '~/tunnel/Makefile'
    force: no
  become: yes
  become_user: tunneler
