---
- name: harden ssh
  include_role:
    name: hardened
    tasks_from: ssh-hardening

- name: Create tunneler user
  user:
    name: tunneler
    shell: /bin/bash
  register: tunneler_created

- name: Setup ssh key for tunneler
  when: tunneler_created is success
  authorized_key:
    user=tunneler
    key="{{ lookup('file','./keys/id_ed25519.pub') }}"

- name: Allow tunneler to access shell via remote
  when: tunneler_created is success
  user:
    name: tunneler
    groups: remote_shell
    append: yes
