---
- name: Install aptitude
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - aptitude
  register: aptitude_installed

- name: Update all apt packages to the latest version
  when: aptitude_installed is success
  apt:
    name: "*"
    state: latest
  register: package_upgraded
