---
- name: Setup ssh key for root
  authorized_key:
    user=root
    key="{{ lookup('file','./keys/id_ed25519.pub') }}"

- name: Disable password SSH
  when: package_upgraded is success
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^\s*(?:#\s*)?(PasswordAuthentication\s+)(?:yes|no)\s*$"
    backrefs=yes
    line="\1no"
  register: ssh_password_disabled
