---
- name: Setup ssh key for root
  authorized_key:
    user=root
    key="{{ lookup('file','./keys/id_ed25519.pub') }}"

- name: Disable password SSH
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^\s*(?:#\s*)?(PasswordAuthentication\s+)(?:yes|no)\s*$"
    backrefs=yes
    line="\1no"
  register: ssh_password_disabled

- name: Create "remote_shell" group
  group:
    name: remote_shell
  register: remote_shell_created

- name: Allow root to access shell via remote
  when: remote_shell_created is success
  user:
    name: root
    groups: remote_shell
    append: yes

- name: Allow group for remote ssh
  when: remote_shell_created is success
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowGroups'
    line: "AllowGroups {{ user_groups | join(' ') }}"
  vars:
    user_groups:
      - remote_shell

- name: Set KexAlgorithms
  when: ssh_password_disabled is success
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^\s*#?\s*KexAlgorithms'
    line: "KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256"

- name: Set MACs
  when: ssh_password_disabled is success
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^\s*#?\s*MACs\b'
    line: "MACs umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512"
