---
- name: Create bin directory for tunneling (tunnelee)
  file:
    path: '~/tunnel/bin'
    state: directory
  become: yes
  become_user: tunnelee

- name: Create bin directory for tunneling (root)
  file:
    path: '~/tunnelee'
    state: directory

- name: Copy tunneling agent to bin
  copy:
    src: "bin/{{ item }}"
    dest: "~/tunnel/bin/{{ item }}"
    mode: '0755'
  become: yes
  become_user: tunnelee
  loop:
    - shadowsocks2
    - gost

- name: Copy Makefile for tunnelee
  copy:
    src: 'tunnelee.Makefile'
    dest: '~/tunnel/Makefile'
    force: no
  become: yes
  become_user: tunnelee

- name: Copy Makefile for root
  copy:
    src: 'root.Makefile'
    dest: '~/tunnelee/Makefile'
    force: no
