---
- name: Create bin directory for tunneling
  file:
    path: '~/tunnel/bin'
    state: directory
  become: yes
  become_user: tunnelee

- name: Allow tunnelee to control iptables
  copy:
    src: 'tunnelee-sudoer.txt'
    dest: '/etc/sudoers.d/tunnelee'
    mode: '0440'
    force: no

- name: Copy tunneling agent to bin
  copy:
    src: "bin/{{ item }}"
    dest: "~/tunnel/bin/{{ item }}"
    mode: '0755'
  become: yes
  become_user: tunnelee
  loop:
    - shadowsocks2
    - gost

- name: Copy Makefile for tunnelee
  copy:
    src: 'tunnelee.Makefile'
    dest: '~/tunnel/Makefile'
    force: no
  become: yes
  become_user: tunnelee
