---
- name: Create tunnelee user
  user:
    name: tunnelee
    shell: /bin/bash
  register: tunnelee_created

- name: Setup ssh key for tunnelee
  when: tunnelee_created is success
  authorized_key:
    user=tunnelee
    key="{{ lookup('file','./keys/id_ed25519.pub') }}"

- name: Allow tunnelee to access shell via remote
  when: tunnelee_created is success
  user:
    name: tunnelee
    groups: remote_shell
    append: yes
